console.log(`# This is autogenerated, please modify gen_app_yaml.js instead

runtime: nodejs
env: flex

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  BOT_USER_OAUTH_ACCESS_TOKEN: '${process.env.BOT_USER_OAUTH_ACCESS_TOKEN}'
  BOTKIT_DEBUG: 0
`);
