const fs = require("fs")
const path = require("path")
const { spawnSync } = require("child_process")

const AUTOGEN_WARNING =
  "This is autogenerated, please modify predeploy.js to change this"

function brianFaces() {
  const BRIAN_FACE_BUCKET_NAME = "brian-faces"

  spawnSync("gsutil", [
    "-m",
    "rsync",
    "-r",
    "./brian_face",
    `gs://${BRIAN_FACE_BUCKET_NAME}/faces`
  ])

  let brianFaceIndex = `// ${AUTOGEN_WARNING}\nmodule.exports = [\n`
  fs.readdirSync("./brian_face").forEach(brianFace => {
    brianFaceIndex += `'https://storage.googleapis.com/${BRIAN_FACE_BUCKET_NAME}/faces/${encodeURIComponent(
      brianFace
    )}',\n`
  })
  brianFaceIndex += `]\n`
  writeFileSync("./src/brianFaces.js", brianFaceIndex)
}

function appYaml() {
  writeFileSync(
    "./app.yaml",
    `# ${AUTOGEN_WARNING}

runtime: nodejs
env: flex

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SLACK_USER_OAUTH_ACCESS_TOKEN: '${process.env.SLACK_USER_OAUTH_ACCESS_TOKEN}'
  BOTKIT_DEBUG: 0
`
  )
}

function writeFileSync(filename, contents) {
  fs.writeFileSync(filename, contents, "utf8")
}

appYaml()
brianFaces()
